### ISSUE TITLE
Problem with Segment Slice and Separator in CSVW

### ISSUE THREAD

**Issue by LinguList** [lexibank/mannburmish#2] opened 2020-11-23 16:48 UTC
@xrotwang, I had before the line:

```python
        args.writer['FormTable', 'Segments'].separator = ' + '
        args.writer['FormTable', 'Segments'].datatype = Datatype.fromvalue(
                {'base': 'string', 'format': "([\\S]+)( [\\S]+)*"})
```
In the code, to make sure that the slicing works for partial cognates. However, since the procedure that segments with the orthography profile yields a string, this will afterwards lead to a situation where the whole list of correct segmentations is ' + '-joined. This did not happen in bodtkhobwa, since the conversion works without an orthoprofile. However, since this passed silent, without anybody noticing (until I looked into the forms.csv), we may want to think of a way to circumvent this problem. 

For now, I just commented the lines out in the lexibank script.

**Comment by xrotwang** [comment] 2020-11-26 17:06
I think the problem is that this "second-level separator" approach isn't really enforced by our tools yet - and `pycldf` doesn't provide any support at all. I think we have two options here:

1. Make this the required format for `Segments` in lexibank and make sure a `list` of `list`s is passed as `Segments` into any method writing a FormTable row.
2. Have `pylexibank` sniff the `'format'` - and decide whether second-level separators are specified, then require either a simple `list` of segments or nested lists.

I think option 1 is better **and** easier to implement. While option 2 seems more flexible, it will lead to a situation where you can't really tell whether the first-level separator separates segments or morphemes - without looking up the regex again.

But a particular problem with your specification above is that the second-level separator (`" "`) is **part** of the first-level separator `" + "`. I can imagine this to lead to weird results.

**Comment by LinguList** [comment] 2020-11-26 20:05
I'd be happy to drop the separator " + " and go with " " in all cases.
This means, that "+" as a segment has to be taken into account by code,
but that is exactly what happens in a datatype such as
lingpy.basictype.lists.

**Comment by LinguList** [comment] 2020-11-26 20:08
So I prefer to make sure that there are no "+ +" instance no
segments[-1] == "+" etc., but leave the question if there is a "+" or
not not to the cldf. Segment.slice will, of course, then have to be
interpreted as part of our non-explicit semantics that there is a second
separator, but I think that is fine, as we have the types for this,
etc., and our methods account for it.

It shows also why it is important to really decide for "+" as the only
separator. We won't allow "#" or "_" to be used.

**Comment by tresoldi** [comment] 2020-11-26 20:47
Sorry to hijack the conversation, but this seems related to the same issue I am having with `naganorgyalrongic`: https://github.com/lexibank/naganorgyalrongic/issues/8#issuecomment-733814982

I'm only mentioning it here so we can keep track of both.

**Comment by xrotwang** [comment] 2020-11-27 06:43
@LinguList So what you are saying is:
1. `Segments` will always be a simple `list` in the CLDF, i.e. there's no secondary separator defined via regex.
2. The "special" segment `+` will be interpreted as morpheme separator by downstream processing software.

Is that right?

If so, I think I agree that this would be the best solution, and also th easiest to communicate: `Segments` is a CLDF thing, `+` to separate morphemes is a `lexibank` thing.

**Comment by xrotwang** [comment] 2020-11-27 06:49
And `SegmentSlice` still works in this scenario - or rather it **only** works in this scenario as intended, i.e. specifying a slice of segments, as opposed to specifying a slice of morphemes in one case and a slice of segments in the other.

**Comment by LinguList** [comment] 2020-11-27 08:38
Yes. That's what I mean. Lexibank now checks also that `+` is only used in specific conditions as separator. 

For the segment slice, however, this would mean that we would have to compute for partial cognates exactly how long they are, right? 

So if I have: `p a + m a` and `p u n + k u` with first element being partial cognates, the segment slice for the cognate for the first word would be 0:2 and for the second it would be 0:3 ?

If you mean this by segmentslice, I consider it impractical, since the typical use case in terms of partial cognates is still that you name them by morpheme, and it would require us to to a lot of checking to validate that the slices are applied correctly.

Or do you mean we stick to our old solution that slices segments by their morpheme structure?

**Comment by xrotwang** [comment] 2020-11-27 08:53
And the slices would also count the `+` as segment. So the second morpheme in `p a + m a` would be `3:5`. If this is impractical, I'd only see the option of adding another column - non-CLDF, but lexibank specific (hence with knowledge about the `+` being a morpheme separator) - to indicate morphemes by morpheme index for partial cognacy.

**Comment by LinguList** [comment] 2020-11-27 08:56
I am perfectly fine with this specific lexibank semantics!

**Comment by LinguList** [comment] 2020-11-27 10:10
So this means, I'll change the data on bodtkhobwa (which is the only ohter dataset) to account for this.

**Comment by LinguList** [comment] 2020-11-27 13:19
I already modified this dataset and also the bodtkhobwa. So we are done with this then.

**Closed as completed** 2020-11-27 13:28 UTC
